// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, unknown> = {
  "components": {
    "breadcrumbs": {
      name: "breadcrumbs",
      type: "registry:ui",
      registryDependencies: ["breadcrumb"],
      files: ["registry/components/ui/breadcrumbs/index.tsx"],
      component: React.lazy(() => import("@/registry/components/ui/breadcrumbs/index.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/components/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/components/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
